name: "Run Papermill Notebook"
description: "Trigger a Papermill job on a JupyterHub/Binder instance."
author: "Jupyter4NFDI"

inputs:
  repo:
    description: "Repository to run Papermill on (org/repo)"
    required: true
  ref:
    description: "Git ref or branch"
    required: false
    default: "HEAD"
  api_url:
    description: "JupyterHub API URL to trigger job"
    required: false
    default: "https://jupyter-jsc-dev1.fz-juelich.de/hub/api/job"
  token:
    description: "JupyterHub API token"
    required: true
  poll_interval:
    description: "Polling interval in seconds"
    required: false
    default: "10"
  max_wait:
    description: "Maximum wait time in seconds"
    required: false
    default: "3600"
  notebook_dirs:
    description: "Optional list of notebook directories (JSON array or comma-separated)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run Papermill job
      run: |
        python ${{ github.action_path }}/run_papermill.py
      shell: bash
      env:
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_API_URL: ${{ inputs.api_url }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_NOTEBOOK_DIRS: ${{ inputs.notebook_dirs }}
        INPUT_POLL_INTERVAL: ${{ inputs.poll_interval }}
        INPUT_MAX_WAIT: ${{ inputs.max_wait }}